# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

for f in ~/.env/common.env ~/.env/web.env ~/.env/aliases ~/.aliases ; do
  [[ -a ${f} ]] && . ${f}
done
