#!/bin/sh
#
# startup script for oracle access mgmt access manager
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle access mgmt weblogic domain
# Required-Start:     $local_fs $remote_fs $named $network $time iamnm
# Required-Stop:      $local_fs $remote_fs $named $network iamnm
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  access management - access manager
# Description:        access management - oam services
### END INIT INFO

user=fmwuser
prog=iamoam
 svc=wls_oam2
ddir=/opt/local/domains/access_test

. /etc/rc.d/init.d/wls-access
. /etc/rc.d/init.d/functions-wls

