# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

for f in _HOSTENV_/env/common.env _HOSTENV_/env/aliases ~/.aliases ; do
  [[ -a ${f} ]] && . ${f}
done
