# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

for f in __HOSTENV__/env/common.env __HOSTENV__/env/aliases ~/.aliases ; do
  [[ -a ${f} ]] && . ${f}
done
