# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

[[ -a ~/.env/common.env ]] && . ~/.env/common.env
[[ -a ~/.env/aliases    ]] && . ~/.env/aliases
[[ -a ~/.aliases        ]] && . ~/.aliases

