#!/bin/sh
#
# startup script for oracle identity mgmt soa server
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle identity mgmt weblogic domain soa services
# Required-Start:     $local_fs $remote_fs $named $network $time iam-node oracle
# Required-Stop:      $local_fs $remote_fs $named $network iam-node oracle
# Should-Start:       
# Should-Stop:        
# Default-Start:      3 4 5
# Default-Stop:       0 1 2 6
# Short-Description:  identity management soa servives
# Description:        identity management middleware for workflows
### END INIT INFO

user=iam
prog=iami-soa
 svc=wls_soa1

. /etc/weblogic/wls-identity
. /etc/rc.d/init.d/functions-wls

