-- drop database schemas (rcu)
--
-- prefix used: DIM2 for identity
--              DAM2 for access
--

DROP USER DIM2_ORASDPM CASCADE;
DROP USER DIM2_OIM CASCADE;
DROP USER DIM2_MDS CASCADE;
DROP USER DIM2_OPSS CASCADE;
DROP USER DIM2_BIPLATFORM CASCADE;
DROP USER DIM2_SOAINFRA CASCADE;

DROP USER DAM2_OMSM CASCADE;
DROP USER DAM2_IAU CASCADE;
DROP USER DAM2_MDS CASCADE;
DROP USER DAM2_OPSS CASCADE;
DROP USER DAM2_OAM CASCADE;
DROP USER DAM2_IAU_APPEND CASCADE;
DROP USER DAM2_IAU_VIEWER CASCADE;

DROP TABLESPACE DAM2_IAS_IAU INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_IAS_OPSS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_IAS_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_MDS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_OAM INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_OAM_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_OMSM_TEMP_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DAM2_OMSM_TS INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE DIM2_BIPLATFORM INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_IAS_OPSS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_IAS_ORASDPM INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_IAS_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_MDS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_OIM INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_OIM_ARCH_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_OIM_LOB INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_OIM_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DIM2_SOAINFRA INCLUDING CONTENTS AND DATAFILES;

DELETE FROM SYSTEM.SCHEMA_VERSION_REGISTRY$ WHERE MRC_NAME LIKE 'D%M2%';

