-- drop schema
--

SELECT 'DROP USER ' || USERNAME || ' CASCADE;' || CHR(13)
FROM  DBA_USERS 
WHERE USERNAME LIKE 'DAM%';

SELECT 'DROP TABLESPACE ' || TABLESPACE_NAME || ' INCLUDING CONTENTS AND DATAFILES;' || CHR(13)
FROM  DBA_TABLESPACES 
WHERE TABLESPACE_NAME LIKE 'D%M2%'

DELETE FROM SYSTEM.SCHEMA_VERSION_REGISTRY$
WHERE MRC_NAME LIKE 'IMK%';

SELECT TABLESPACE_NAME
FROM  DBA_TABLESPACES
WHERE TABLESPACE_NAME LIKE 'IMK%';

SELECT * 
FROM  SYSTEM.SCHEMA_VERSION_REGISTRY$;

