#  Oracle Identity and Access Management
#  vi: set ft=ruby :
#

VAGRANTFILE_API_VERSION = "2"

IP_SRV="192.168.168.10"     # server ip address
IP_LBFE=IP_SRV              # frontend load balancer
IP_DBS1=IP_SRV              # database server
IP_NFSI="10.80.1.4"         # existing nfs with install images

app_name    = "iamvs.agoracon.at"
app_box     = "centos67fusion"
app_box_url = "https://agoracon.at/boxes/centos67fusion.box"
$hostfile   = "# ...cant touch this
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1                                         localhost6 localhost6.localdomain6
#{IP_SRV}                    iamvs.agoracon.at            iamvs
#{IP_SRV}              oradb.iamvs.agoracon.at            oradb
#{IP_LBFE}            access.iamvs.agoracon.at           access
#{IP_LBFE}      access-admin.iamvs.agoracon.at     access-admin
#{IP_LBFE}        access-api.iamvs.agoracon.at       access-api
#{IP_LBFE}     access-mobile.iamvs.agoracon.at    access-mobile
#{IP_LBFE}          identity.iamvs.agoracon.at         identity
#{IP_LBFE}    identity-admin.iamvs.agoracon.at   identity-admin
#{IP_LBFE}      identity-api.iamvs.agoracon.at     identity-api
#{IP_LBFE}         dir-admin.iamvs.agoracon.at        dir-admin
#{IP_LBFE}             omsas.iamvs.agoracon.at            omsas
#{IP_NFSI}                              images
"

$images = "images:/export/oracle /mnt/oracle nfs rw,bg 0 0\n"
# $exports, $fstab = "", "#{$images}"
# [ '/opt/fmw/config',
#   '/opt/fmw/products',
#   '/opt/fmw/lcm',
#   '/opt/fmw/etc' ].each do |d|
#   $exports << "#{d} 192.168.168.0/24(rw,async,no_subtree_check)\n"
#   $fstab   << "oim1:#{d} #{d} nfs rw,async 0 0\n"
# end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "hosts-file", type: "shell" do |s|
    s.inline = "echo '#{$hostfile}' > /etc/hosts"
  end

  config.vm.provision "root", type: "shell" do |s|
    s.inline ="/vagrant/user-config/env/root-script.sh"
  end

  config.vm.provision "nfs", type: "shell" do |s|
    s.inline = "echo '#{$images}' >>/etc/fstab;
      mount /mnt/oracle"
  end

  # config.vm.provision "ssh-key", type: "shell" do |s|
  #   s.inline = "su - fmwuser -c 'mkdir -p ~/.ssh;
  #     chmod 0700 ~/.ssh; 
  #     cp /vagrant/user-config/hostenv/ssh/* ~/.ssh/; 
  #     chmod 0644 ~/.ssh/*; 
  #     chmod 0600 ~/.ssh/id_rsa'"
  # end

  config.vm.define :app, primary: true do |app|
    app.vm.box          = app_box
    app.vm.hostname     = app_name
    app.vm.box_url      = app_box_url
    app.vm.boot_timeout = 120
    app.ssh.username    = 'fmwuser'

    app.vm.network :private_network, ip: IP_SRV
    app.vm.provider :virtualbox do |v|
      v.name   = app_name
      v.cpus   = 4
      v.memory = 32 * 1024
    end

  end

  config.vm.provision "database", type: "shell" do |s|
    s.inline = "su - oracle  -c 'DEPLOYER=/vagrant /vagrant/database  | /usr/bin/tee /tmp/prov-database.log'"
  end

  config.vm.provision "iam", type: "shell" do |s|
    s.inline = "su - fmwuser -c 'DEPLOYER=/vagrant /vagrant/iam provision | /usr/bin/tee /tmp/prov-iam.log'"
  end

  #config.vm.provision "load-balancer", type: "shell" do |s|
  #  s.inline = "/vagrant/user-config/env/load-balancer.sh #{IP_LBFE}"
  #end
end

