#!/bin/sh
#
# startup script for oracle identity mgmt weblogic admin server
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle identity mgmt weblogic domain admin server
# Required-Start:     $local_fs $remote_fs $named $network $time iam-node oracle
# Required-Stop:      $local_fs $remote_fs $named $network iam-node oracle
# Should-Start:       
# Should-Stop:        
# Default-Start:      3 4 5
# Default-Stop:       0 1 2 6
# Short-Description:  identity management weblogic adminserver
# Description:        identity management services - admin
### END INIT INFO

user=iam
prog=iami-admin
 svc=AdminServer

. /etc/weblogic/iamcfg-identity
. /etc/rc.d/init.d/functions-wls

