#!/bin/sh
#
# startup script for oracle access mgmt weblogic admin server
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle access mgmt weblogic domain
# Required-Start:     $local_fs $remote_fs $named $network $time iam-node oracle
# Required-Stop:      $local_fs $remote_fs $named $network iam-node oracle
# Should-Start:       
# Should-Stop:        
# Default-Start:      3 4 5
# Default-Stop:       0 1 2 6
# Short-Description:  access management weblogic adminserver
# Description:        access management services - admin
### END INIT INFO

user=iam
prog=iama-admin
 svc=AdminServer

. /etc/weblogic/iamcfg-access
. /etc/rc.d/init.d/functions-wls

