#!/bin/sh
#
# startup script for oracle identity mgmt soa server
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle identity mgmt weblogic domain soa services
# Required-Start:     $local_fs $remote_fs $named $network $time iamnm oracle
# Required-Stop:      $local_fs $remote_fs $named $network iamnm oracle
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  identity management soa servives
# Description:        identity management middleware for workflows
### END INIT INFO

user=iam
prog=iamoimsoa
 svc=wls_soa1

. /etc/rc.d/init.d/iamcfg-identity
. /etc/rc.d/init.d/functions-wls

