#!/bin/sh
#
# startup script for oracle webtier
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           Oracle WebTier
# Required-Start:     $local_fs $remote_fs $syslog $named $network $time
# Required-Stop:      $local_fs $remote_fs $syslog $named $network
# Should-Start:       
# Should-Stop:        
# Default-Start:      3 4 5
# Default-Stop:       0 1 2 6
# Short-Description:  start and stop the Oracle WebTier stack
# Description:        WebCache web accelerator and Apache HTTP server
### END INIT INFO
#
# Source function library.
. /etc/rc.d/init.d/functions
# Source networking configuration.
. /etc/sysconfig/network

svcuser=fmwuser
prog=iam-web

# Source instance settings
export     DOMAIN_HOME=/opt/local/fmw/instances/ohs2
export         MW_HOME=/opt/fmw/products/web
export     ORACLE_HOME=${MW_HOME}/ohs
export         WG_HOME=${MW_HOME}/webgate

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

export            PATH=${DOMAIN_HOME}/bin:${ORACLE_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${ORACLE_HOME}/lib:${WG_HOME}/webgate/ohs/lib
prg=${DOMAIN_HOME}/bin/opmnctl

[ -f $opmnctl ] || exit 0

RETVAL=0

stop() {
  local retval=0
  echo -n "Shutting down $0: "
  su $svcuser -c "$prg shutdown"
  retval=$?
  return $retval
}

start() {
  echo -n "Starting $0: "
  su $svcuser -c "$prg startall"
  retval=$?
  return $retval
}

status() {
  # opmnctl returns
  #   0..  running processes
  #   2..  no processes
  su $svcuser -c "$prg status"
  retval=$?
  return $retval
}  
 
# See how we were called.
case "$1" in
  start)
        if [ $UID -ne 0 ] ; then
            echo "User has insufficient privilege."
            exit 4
        fi
        start
	      RETVAL=$?
        echo
        ;;
  stop)
	status
        retval=$?
        if [ "$retval" -eq 0 ]; then
          stop
          RETVAL=$?
        fi
        RETVAL=$?
        echo
        ;;
  status)
      	status
      	RETVAL=$?
      	;;
  restart)
      	$0 stop
      	$0 start
      	RETVAL=$?
      	;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
esac

exit $RETVAL

