#!/bin/sh
#
# Startup script for Oracle RDMBS
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           Oracle Relational Database Management System
# Required-Start:     $local_fs $remote_fs $syslog $named $network $time
# Required-Stop:      $local_fs $remote_fs $syslog $named $network
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Oracle RDBMS
# Description:        Relational Database Managemen System, instances in /etc/oratab
### END INIT INFO
#
# Source function library.
. /etc/rc.d/init.d/functions
# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

prog=oracle
LOCKFILE=/var/lock/subsys/oracle
ORACLE_USER=oracle
PPROC=ora_pmon_miercoles

case "$1" in
'start')
   if [ -f $LOCKFILE ]; then
      echo $0 already running.
      exit 1
   fi
   echo -n $"Starting Oracle Database:"
   su - $ORACLE_USER -c '$ORACLE_HOME/bin/lsnrctl start'
   su - $ORACLE_USER -c '$ORACLE_HOME/bin/dbstart $ORACLE_HOME'
#  su - $ORACLE_USER -c '$ORACLE_HOME/bin/emctl start dbconsole'
   touch $LOCKFILE
   ;;
'stop')
   if [ ! -f $LOCKFILE ]; then
      echo $0 already stopping.
      exit 1
   fi
   echo -n $"Stopping Oracle Database:"
   su - $ORACLE_USER -c '$ORACLE_HOME/bin/lsnrctl stop'
   su - $ORACLE_USER -c '$ORACLE_HOME/bin/dbshut $ORACLE_HOME'
#  su - $ORACLE_USER -c '$ORACLE_HOME/bin/emctl stop dbconsole'
   rm -f $LOCKFILE
   ;;
'restart')
   $0 stop
   $0 start
   ;;
'status')
   # if [ -f $LOCKFILE ]; then
   if pgrep -f ${PPROC} >/dev/null ; then
      echo "service ${prog} is running"
      exit 0
   else
      echo "service ${prog} is stopped"
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 [start|stop|status]"
   exit 1
esac

exit 0

