#!/bin/sh
#
# startup script for oracle identity mgmt identity manager
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle identity mgmt weblogic domain
# Required-Start:     $local_fs $remote_fs $named $network $time nfs iam-node
# Required-Stop:      $local_fs $remote_fs $named $network nfs iam-node
# Should-Start:       
# Should-Stop:        
# Default-Start:      3 4 5
# Default-Stop:       0 1 2 6
# Short-Description:  identity management - identity manager
# Description:        identity management - idm services
### END INIT INFO

user=fmwuser
prog=iami-oim
 svc=wls_oim1
ddir=/opt/local/domains/identity_test

. /etc/weblogic/wls-identity
. /etc/rc.d/init.d/functions-wls

