#!/bin/sh
#
# startup script for oracle identity mgmt identity manager
#                     horst.kapfenberger@agoracon.at
#
### BEGIN INIT INFO
# Provides:           oracle identity mgmt weblogic domain
# Required-Start:     $local_fs $remote_fs $named $network $time iam-nodemanager
# Required-Stop:      $local_fs $remote_fs $named $network iam-nodemanager
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  identity management - identity manager
# Description:        identity management - idm services
### END INIT INFO

user=fmwuser
prog=iamoim
 svc=wls_oim1
ddir=/opt/local/domains/identity_test

. /etc/rc.d/init.d/wls-identity
. /etc/rc.d/init.d/functions-wls

