#  Oracle Identity and Access Management
#  vi: set ft=ruby :
#

VAGRANTFILE_API_VERSION = "2"

app_name       = "iamvs.agoracon.at"
app_ip         = "192.168.168.250"
app_box        = "centos66min"
app_box_url    = "https://agoracon.at/boxes/centos66min.box"
#app_box_sha    = "bce6a99728ceaeb017f475ee734f676390cf8c49b6aed721a3247c204daa507f"

$frontend_ip = "192.168.168.250"
$hostfile = "# ...cant touch this
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1                                         localhost6 localhost6.localdomain6
192.168.168.250               iamvs.agoracon.at        iamvs
192.168.168.250         oradb.iamvs.agoracon.at
#{$frontend_ip}   idminternal.iamvs.agoracon.at
#{$frontend_ip}           sso.iamvs.agoracon.at
192.168.168.1                           images
"

$images = "images:/Volumes/hext01/install/oracle /mnt/oracle nfs rw,bg,rsize=32768,wsize=32768 0 0\n"
# $exports, $fstab = "", "#{$images}"
# [ '/l/ora/config',
#   '/l/ora/products',
#   '/l/ora/lcm',
#   '/l/ora/etc' ].each do |d|
#   $exports << "#{d} 192.168.168.0/24(rw,async,no_subtree_check)\n"
#   $fstab   << "oim1:#{d} #{d} nfs rw,async 0 0\n"
# end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "hosts-file", type: "shell" do |s|
    s.inline = "echo '#{$hostfile}' > /etc/hosts"
  end

  config.vm.provision "root", type: "shell" do |s|
    s.inline ="/vagrant/user-config/env/root-script.sh"
  end

  config.vm.provision "nfs", type: "shell" do |s|
    s.inline = "echo '#{$images}' >>/etc/fstab;
      mount /mnt/oracle"
  end

  config.vm.provision "vbox", type: "shell" do |s|
    s.inline = "/mnt/oracle/vbox5/VBoxLinuxAdditions.run"
  end

  # config.vm.provision "ssh-key", type: "shell" do |s|
  #   s.inline = "su - fmwuser -c 'mkdir -p ~/.ssh;
  #     chmod 0700 ~/.ssh; 
  #     cp /vagrant/user-config/hostenv/ssh/* ~/.ssh/; 
  #     chmod 0644 ~/.ssh/*; 
  #     chmod 0600 ~/.ssh/id_rsa'"
  # end

  config.vm.define :app, primary: true do |app|
    app.vm.box          = app_box
    app.vm.hostname     = app_name
    app.vm.box_url      = app_box_url
    app.vm.boot_timeout = 120
    app.ssh.username    = 'vagrant'

    app.vm.network :private_network, ip: app_ip
    app.vm.provider :virtualbox do |v|
      v.name   = app_name
      v.cpus   = 4
      #v.memory = 12288
      v.memory = 10240
    end

  end

  config.vm.provision "database", type: "shell" do |s|
    s.inline = "su - oracle  -c 'DEPLOYER=/vagrant /vagrant/db.sh  | /usr/bin/tee /tmp/prov-dbs.log'"
  end

  config.vm.provision "iam", type: "shell" do |s|
    s.inline = "su - fmwuser -c 'DEPLOYER=/vagrant /vagrant/iam provision'"
  end

  #config.vm.provision "load-balancer", type: "shell" do |s|
  #  s.inline = "/vagrant/user-config/env/load-balancer.sh #{$frontend_ip}"
  #end
end

